config/routes.rb
Rails.application.routes.draw do
  root to: "medics#index"
  get 'medics/index'
  get 'my_medics', to: 'medics#my_medics'
  get 'search_medic', to: 'medics#search'

  resources :medics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medic.rb
class Medic < ApplicationRecord

  def self.matches(field_name, param) 
    where("#{field_name} ilike ?", "%#{param}%")
  end

  def self.search(param)
    param.strip!
    to_send_back = (ccg_matches(param) + postcode_matches(param) + practice_name_matches(param) + address_matches(param) + list_size_matches(param) + brick_matches(param) + telephone_matches(param)).uniq 
    return nil unless to_send_back
    to_send_back
  end

  def self.ccg_matches(param)
    matches('ccg', param)
  end

  # def self.group_matches(param) removed this as was creating error - possibly group is a reserved term?
  #   matches('group', param)
  # end

  def self.postcode_matches(param)
    matches('postcode', param)
  end

  def self.practice_name_matches(param)
    matches('practice_name', param)
  end

  def self.address_matches(param)
    matches('address', param)
  end

  def self.list_size_matches(param)
    matches('list_size', param)
  end

  def self.brick_matches(param)
    matches('brick', param)
  end

  def self.telephone_matches(param)
    matches('telephone', param)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  
  def index 
    
  end

  def show 
    @medic = Medic.find(params[:id])
  end

  def search 
    if params[:medic].present?
      @medics = params[:medic].present?
      @medics = Medic.search(params[:medic])
      if @medics && @medics.count > 0
        respond_to do |format|
        format.js { render partial: 'medics/medic_result' }
        end
        else
        respond_to do |format|
        flash.now[:danger] = "There are no result's found for this request.."
        format.js { render partial: 'medics/medic_result' }
        end
        end
        else
        respond_to do |format|
        flash.now[:danger] = "Please enter a name or postcode to search.."
        format.js { render partial: 'medics/medic_result' }
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close ml-2" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">Created by Vincent Walker</footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-between">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-nav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse dual-nav w-100 ">
  <ul class="navbar-nav">
    <li class="nav-item">
    <%= link_to 'Home', root_path, class: "btn btn btn-outline-light " %>
    </li>
  </ul>
    </div>
    <div class="navbar-collapse collapse dual-nav w-100">
      <ul class="nav navbar-nav ml-auto">
      <%# if logged_in? %>
      <li class="nav-item right"> <%= link_to 'Look up a Medical Center', '#', class: "btn btn btn-outline-light " %></li>
      <%# end %>
      <%# if current_user %> 
      <li><%#= link_to "Log Out", login_path, method: :delete, class: "btn btn-default" %></li>
      <%# else %>
      <li><%#= link_to "Log in", login_path, class: "btn btn-default" %></li>
      <%# end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindAMedic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv=“X-UA-Compatible” content=“IE=edge”>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/medics/_medic_result.html.erb
<div class="container">
<div class="ml-5">
  <%= render 'layouts/flash' %>
</div>
<% if @medics %>
  <!-- <div class="card card-header results-block"> -->
  
    <table class="table table-bordered tabel-hover">
      <tbody>
        <% @medics.each do |medic| %>
          <tr class="card card-header  mb-4 medic-description">
            <td class="mt-1"><strong>Name of Medical Center: </strong> <%= medic.practice_name %></td>
            <td class="mt-1"><strong class="ml-2 ">Address: </strong> <%= medic.address %></td>
            <td class="mt-1"><strong class="ml-2 ">Postcode: </strong> <%= medic.postcode %></td>
            <td class="mt-1"><%= link_to "View #{medic.practice_name}'s Details", medic_path(medic),class: "btn btn-outline-primary btn-sm ml-2" %>
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
  
<% end %> 
</div>

app/views/medics/_medic_result.js.erb
document.querySelector('#medic-results').innerHTML = "<%= j render 'medics/medic_result.html' %>"

app/views/medics/_my_medics.html.erb
<div class="container">
  <div class="row mt-2">
    <h1>Search for a Medical Center</h1>
  </div>

<div class='search-area mx-auto'></div>
  <%= form_tag search_medic_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-8 no-right-padding for-phone">
        <%= text_field_tag :medic, params[:medic], placeholder: "Look up Medical Center", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-4 no-left-padding for-phone">
        <%= button_tag type: :submit, class: "btn btn-dark btn-lg" do %>
        <i class="fa fa-search "></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

<div id="medic-results">
</div>

app/views/medics/index.html.erb
<div class="col-md-8 offset-md-3">
  <%= render "medics/my_medics" %>
</div>



  

app/views/medics/show.html.erb
<div class="container">
<div class="row mt-2">
    <h2 class="mx-auto">Details for: <%= @medic.practice_name%></h2>
</div>
  <table class="table table-bordered table-hover show-details">
    <tbody>
        <tr class="card card-header">
          <td><strong>Which CCG: </strong><%= @medic.ccg %></td>
          <td><strong>Type of Health care: </strong><%= @medic.group %></td>
          <td><strong>Name of Practice: </strong><%= @medic.practice_name%></td>
          <td><strong>Address: </strong><%= @medic.address %></td>
          <td><strong>Postcode: </strong><%= @medic.postcode %></td>
          <td><strong>Area: </strong><%= @medic.brick %></td>
          <td><strong>Number of registered patients: </strong><%= @medic.list_size %></td>
          <td><strong>Telephone Number: </strong><%= (@medic.telephone).to_i %></td>
        </tr>
    </tbody>
  </table>
</div>

app/views/medics/spare.html.erb
<div class="table-responsive">
    <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>CCG</th>
        <th>Group</th>
        <th>Post Code</th>
        <th>Practice Name</th>
        <th>Address</th>
        <th>List Size</th>
        <th>Brick</th>
        <th>Telephone</th>
      </tr>
    </thead>
    <tbody>
      <% @medics.each do |medic| %>
        <tr>
          <td><%= medic.ccg %></td>
          <td><%= medic.group %></td>
          <td><%= medic.postcode %></td>
          <td><%= medic.practice_name%></td>
          <td><%= medic.address %></td>
          <td><%= medic.list_size %></td>
          <td><%= medic.brick %></td>
          <td><%= (medic.telephone).to_i %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
  </div>
<div>